"""empty message

Revision ID: 81c04fbc557c
Revises: 43a66726c680
Create Date: 2022-06-07 12:27:56.433037

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '81c04fbc557c'
down_revision = '43a66726c680'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('UpcomingShow')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('UpcomingShow',
    sa.Column('id', sa.INTEGER(), server_default=sa.text('nextval(\'"UpcomingShow_id_seq"\'::regclass)'), autoincrement=True, nullable=False),
    sa.Column('venue_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('artist_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('start_time', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['artist_id'], ['Artist.id'], name='UpcomingShow_artist_id_fkey'),
    sa.ForeignKeyConstraint(['venue_id'], ['Venue.id'], name='UpcomingShow_venue_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='UpcomingShow_pkey')
    )
    # ### end Alembic commands ###
